from .cantons_controller import cantons_router
from .categories_controller import categories_router
from .districts_controller import district_router
from .legends_controller import legends_router
from .provinces_controller import provinces_router